"""
Typed reference stub for the embedded raw `PyImGui` module.

This file is intentionally more verbose than the facade stub. Its purpose is
discoverability:
- show the major categories of the bound API
- document the return-value conventions used by this binding layer
- make editor completion usable without already knowing Dear ImGui by heart

Important binding conventions in this project:
- Widgets that normally mutate an "in/out" value return the new value instead.
  Example: `slider_float(...) -> float`, `input_text(...) -> str`.
- `begin_with_close()` and `begin_tab_item_closable()` return tuples with both
  visibility and the updated open state.
- Most flags are plain `IntFlag` classes and can be OR-ed together.
"""

from enum import IntEnum, IntFlag
from typing import Any, Optional, Sequence, overload


class Vec2:
    """2D float vector used by most layout and drawing APIs."""

    x: float
    y: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float = ...) -> None: ...
    @overload
    def __init__(self, value: Sequence[float]) -> None: ...


class Vec4:
    """4D float vector used by colors and some geometry APIs."""

    x: float
    y: float
    z: float
    w: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float = ..., z: float = ..., w: float = ...) -> None: ...
    @overload
    def __init__(self, value: Sequence[float]) -> None: ...


class SortDirection(IntEnum):
    None_: int
    Ascending: int
    Descending: int


# Flags and enums. The raw module contains the full sets; these class shells are
# here to make completion group them sensibly.
class WindowFlags(IntFlag):
    NoFlag: int
    NoTitleBar: int
    NoResize: int
    NoMove: int
    NoScrollbar: int
    NoScrollWithMouse: int
    NoCollapse: int
    AlwaysAutoResize: int
    NoBackground: int
    NoSavedSettings: int
    NoMouseInputs: int
    MenuBar: int
    HorizontalScrollbar: int
    NoFocusOnAppearing: int
    NoBringToFrontOnFocus: int
    AlwaysVerticalScrollbar: int
    AlwaysHorizontalScrollbar: int
    NoNavInputs: int
    NoNavFocus: int
    UnsavedDocument: int
    NoDocking: int
    NoInputs: int


class ChildFlags(IntFlag): ...
class InputTextFlags(IntFlag): ...
class TreeNodeFlags(IntFlag): ...
class PopupFlags(IntFlag): ...
class SelectableFlags(IntFlag): ...
class ComboFlags(IntFlag): ...
class TabBarFlags(IntFlag): ...
class TabItemFlags(IntFlag): ...
class FocusedFlags(IntFlag): ...
class HoveredFlags(IntFlag): ...
class DockNodeFlags(IntFlag): ...
class DragDropFlags(IntFlag): ...
class SliderFlags(IntFlag): ...
class ButtonFlags(IntFlag): ...
class TableFlags(IntFlag): ...
class TableColumnFlags(IntFlag): ...
class TableRowFlags(IntFlag): ...
class DrawFlags(IntFlag): ...
class ColorEditFlags(IntFlag): ...
class ImGuiCond(IntFlag): ...
class MouseButton(IntEnum): ...
class MouseCursor(IntEnum): ...
class ImGuiCol(IntEnum): ...
class ImGuiStyleVar(IntEnum): ...


class TableColumnSortSpecs:
    """Metadata for one column in a sortable ImGui table."""

    ColumnIndex: int
    SortDirection: int


class TableSortSpecs:
    """Sort metadata returned by `table_get_sort_specs()`."""

    SpecsDirty: bool
    SpecsCount: int


class ImGuiStyle:
    """Direct style snapshot exposed from Dear ImGui."""


class ImGuiIO:
    """Safe copy of the important fields from `ImGuiIO`."""

    display_size_x: float
    display_size_y: float
    delta_time: float
    ini_saving_rate: float
    ini_filename: str
    log_filename: str
    mouse_double_click_time: float
    mouse_double_click_max_dist: float
    mouse_drag_threshold: float
    mouse_pos_x: float
    mouse_pos_y: float
    mouse_wheel: float
    mouse_wheel_h: float
    framerate: float
    key_ctrl: bool
    key_shift: bool
    key_alt: bool
    key_super: bool
    want_capture_mouse: bool
    want_capture_keyboard: bool
    want_text_input: bool
    want_set_mouse_pos: bool
    want_save_ini_settings: bool
    app_focus_lost: bool
    metrics_render_vertices: int
    metrics_render_indices: int
    metrics_active_windows: int


class StyleConfig:
    """Editable style-copy helper used by the binding layer."""

    def Pull(self) -> None: ...
    def Push(self) -> None: ...
    def Reset(self) -> None: ...


# Core / state
def get_io() -> ImGuiIO: ...
def get_style() -> ImGuiStyle: ...
def get_version() -> str: ...
def show_style_selector(label: str) -> bool: ...
def show_font_selector(label: str) -> None: ...
def style_colors_dark(dst: object | None = ...) -> None: ...
def style_colors_light(dst: object | None = ...) -> None: ...
def style_colors_classic(dst: object | None = ...) -> None: ...
def get_style_color_name(idx: int) -> str: ...


# Window creation / lifecycle
def begin(name: str, p_open: object | None = ..., flags: int = ...) -> bool: ...
def begin_with_close(name: str, p_open: bool, flags: int = ...) -> tuple[bool, bool]: ...
def end() -> None: ...
def begin_child(id: str, size: Vec2 = ..., child_flags: int = ..., window_flags: int = ...) -> bool: ...
def end_child() -> None: ...
def begin_disabled(disabled: bool = ...) -> None: ...
def end_disabled() -> None: ...


# Window setup / queries
def set_next_window_pos(pos: Vec2, cond: int = ..., pivot: Vec2 = ...) -> None: ...
def set_next_window_size(size: Vec2, cond: int = ...) -> None: ...
def set_next_window_size_constraints(size_min: Vec2, size_max: Vec2) -> None: ...
def set_next_window_content_size(size: Vec2) -> None: ...
def set_next_window_collapsed(collapsed: bool, cond: int = ...) -> None: ...
def set_next_window_focus() -> None: ...
def set_next_window_bg_alpha(alpha: float) -> None: ...
def set_next_window_scroll(scroll: Vec2) -> None: ...
def set_next_window_viewport(viewport_id: int) -> None: ...
def set_window_pos(pos: Vec2, cond: int = ...) -> None: ...
def set_window_size(size: Vec2, cond: int = ...) -> None: ...
def set_window_collapsed(collapsed: bool, cond: int = ...) -> None: ...
def set_window_focus(name: str) -> None: ...
def get_window_pos() -> Vec2: ...
def get_window_size() -> Vec2: ...
def get_window_width() -> float: ...
def get_window_height() -> float: ...
def get_content_region_avail() -> Vec2: ...
def is_window_appearing() -> bool: ...
def is_window_collapsed() -> bool: ...
def is_window_focused(flags: int = ...) -> bool: ...
def is_window_hovered(flags: int = ...) -> bool: ...
def is_rect_visible(size: Vec2) -> bool: ...


# Layout
def separator() -> None: ...
def separator_text(label: str) -> None: ...
def same_line(offset_from_start_x: float = ..., spacing: float = ...) -> None: ...
def spacing() -> None: ...
def new_line() -> None: ...
def dummy(size: Vec2) -> None: ...
def indent(indent_w: float = ...) -> None: ...
def unindent(indent_w: float = ...) -> None: ...
def align_text_to_frame_padding() -> None: ...
def get_frame_height() -> float: ...
def get_frame_height_with_spacing() -> float: ...
def get_font_size() -> float: ...
def push_font(font_index: int = ...) -> None: ...
def pop_font() -> None: ...
def push_font_scaled(font_index: int, scale: float = ...) -> None: ...
def pop_font_scaled() -> None: ...
def push_style_font(style: int, size: float = ...) -> None: ...
def push_font_size(size: float) -> None: ...
def get_global_font_scale() -> float: ...
def set_global_font_scale(scale: float) -> None: ...


# Text
def text_unformatted(text: str, text_end: Optional[str] = ...) -> None: ...
def text_link(label: str) -> bool: ...
def text_link_open_url(label: str, url: Optional[str] = ...) -> bool: ...
def TextV(fmt: str, args: Sequence[str]) -> None: ...
def TextColoredV(color: Vec4, fmt: str, args: Sequence[str]) -> None: ...
def TextDisabledV(fmt: str, args: Sequence[str]) -> None: ...
def TextWrappedV(fmt: str, args: Sequence[str]) -> None: ...
def LabelTextV(label: str, fmt: str, args: Sequence[str]) -> None: ...
def BulletTextV(fmt: str, args: Sequence[str]) -> None: ...
def text(text: str) -> None: ...
@overload
def text_colored(color: Vec4, text: str) -> None: ...
@overload
def text_colored(r: float, g: float, b: float, a: float, text: str) -> None: ...
def text_disabled(text: str) -> None: ...
def text_wrapped(text: str) -> None: ...
def bullet_text(text: str) -> None: ...
def label_text(label: str, text: str) -> None: ...


# Widgets
@overload
def button(label: str, size: Vec2 = ...) -> bool: ...
@overload
def button(label: str, width: float = ..., height: float = ...) -> bool: ...
def small_button(label: str) -> bool: ...
def invisible_button(str_id: str, size: Vec2, flags: int = ...) -> bool: ...
def arrow_button(str_id: str, dir: int) -> bool: ...
def checkbox(label: str, value: bool) -> bool: ...
def checkbox_flags(label: str, flags: int, flags_value: int) -> int: ...
def radio_button(label: str, value: int, v_button: int) -> int: ...
def progress_bar(fraction: float, size_arg: Vec2 = ..., overlay: Optional[str] = ...) -> None: ...
def bullet() -> None: ...


# Sliders / drags. Project convention: each function returns the updated value.
def slider_float(label: str, v: float, v_min: float, v_max: float, format: str = ..., flags: int = ...) -> float: ...
def slider_int(label: str, v: int, v_min: int, v_max: int, format: str = ..., flags: int = ...) -> int: ...
def slider_angle(label: str, v_rad: float, v_degrees_min: float = ..., v_degrees_max: float = ..., format: str = ..., flags: int = ...) -> float: ...
def v_slider_float(label: str, size: Vec2, v: float, v_min: float, v_max: float, format: str = ..., flags: int = ...) -> float: ...
def v_slider_int(label: str, size: Vec2, v: int, v_min: int, v_max: int, format: str = ..., flags: int = ...) -> int: ...
def slider_float2(label: str, v: Sequence[float], v_min: float, v_max: float, format: str = ..., flags: int = ...) -> list[float]: ...
def slider_float3(label: str, v: Sequence[float], v_min: float, v_max: float, format: str = ..., flags: int = ...) -> list[float]: ...
def slider_float4(label: str, v: Sequence[float], v_min: float, v_max: float, format: str = ..., flags: int = ...) -> list[float]: ...
def slider_int2(label: str, v: Sequence[int], v_min: int, v_max: int, format: str = ..., flags: int = ...) -> list[int]: ...
def slider_int3(label: str, v: Sequence[int], v_min: int, v_max: int, format: str = ..., flags: int = ...) -> list[int]: ...
def slider_int4(label: str, v: Sequence[int], v_min: int, v_max: int, format: str = ..., flags: int = ...) -> list[int]: ...
def drag_float(label: str, v: float, v_speed: float = ..., v_min: float = ..., v_max: float = ..., format: str = ..., flags: int = ...) -> float: ...
def drag_float_range2(label: str, v_current_min: float, v_current_max: float, v_speed: float = ..., v_min: float = ..., v_max: float = ..., format: str = ..., format_max: Optional[str] = ..., flags: int = ...) -> tuple[float, float]: ...
def drag_int(label: str, v: int, v_speed: float = ..., v_min: int = ..., v_max: int = ..., format: str = ..., flags: int = ...) -> int: ...
def drag_int_range2(label: str, v_current_min: int, v_current_max: int, v_speed: float = ..., v_min: int = ..., v_max: int = ..., format: str = ..., format_max: Optional[str] = ..., flags: int = ...) -> tuple[int, int]: ...
def drag_float2(label: str, v: Sequence[float], v_speed: float = ..., v_min: float = ..., v_max: float = ..., format: str = ..., flags: int = ...) -> list[float]: ...
def drag_float3(label: str, v: Sequence[float], v_speed: float = ..., v_min: float = ..., v_max: float = ..., format: str = ..., flags: int = ...) -> list[float]: ...
def drag_float4(label: str, v: Sequence[float], v_speed: float = ..., v_min: float = ..., v_max: float = ..., format: str = ..., flags: int = ...) -> list[float]: ...
def drag_int2(label: str, v: Sequence[int], v_speed: float = ..., v_min: int = ..., v_max: int = ..., format: str = ..., flags: int = ...) -> list[int]: ...
def drag_int3(label: str, v: Sequence[int], v_speed: float = ..., v_min: int = ..., v_max: int = ..., format: str = ..., flags: int = ...) -> list[int]: ...
def drag_int4(label: str, v: Sequence[int], v_speed: float = ..., v_min: int = ..., v_max: int = ..., format: str = ..., flags: int = ...) -> list[int]: ...


# Input editors
def input_float(label: str, v: float, step: float = ..., step_fast: float = ..., format: str = ..., flags: int = ...) -> float: ...
def input_float2(label: str, v: Sequence[float], format: str = ..., flags: int = ...) -> list[float]: ...
def input_float3(label: str, v: Sequence[float], format: str = ..., flags: int = ...) -> list[float]: ...
def input_float4(label: str, v: Sequence[float], format: str = ..., flags: int = ...) -> list[float]: ...
def input_int(label: str, v: int, step: int = ..., step_fast: int = ..., flags: int = ...) -> int: ...
def input_int2(label: str, v: Sequence[int], flags: int = ...) -> list[int]: ...
def input_int3(label: str, v: Sequence[int], flags: int = ...) -> list[int]: ...
def input_int4(label: str, v: Sequence[int], flags: int = ...) -> list[int]: ...
def input_double(label: str, v: float, step: float = ..., step_fast: float = ..., format: str = ..., flags: int = ...) -> float: ...
def input_text(label: str, text: str = ..., flags: int = ...) -> str: ...
def input_text_with_hint(label: str, hint: str, text: str = ..., flags: int = ...) -> str: ...
def input_text_multiline(label: str, text: str = ..., size: Vec2 = ..., flags: int = ...) -> str: ...


# Combo / lists / selection
def begin_combo(label: str, preview_value: str, flags: int = ...) -> bool: ...
def end_combo() -> None: ...
def combo(label: str, current_item: int, items: Sequence[str]) -> int: ...
def begin_list_box(label: str, size: Vec2 = ...) -> bool: ...
def end_list_box() -> None: ...
def list_box(label: str, current_item: int, items: Sequence[str], height_in_items: int = ...) -> int: ...
def selectable(label: str, selected: bool = ..., flags: int = ..., size: Vec2 = ...) -> bool: ...


# Colors
def color_edit3(label: str, col: Sequence[float], flags: int = ...) -> list[float]: ...
def color_edit4(label: str, col: Sequence[float], flags: int = ...) -> list[float]: ...
def color_picker3(label: str, col: Sequence[float], flags: int = ...) -> list[float]: ...
def color_picker4(label: str, col: Sequence[float], flags: int = ...) -> list[float]: ...
def color_button(desc_id: str, col: Vec4, flags: int = ..., size: Vec2 = ...) -> bool: ...
def set_color_edit_options(flags: int) -> None: ...
def color_convert_u32_to_float4(value: int) -> Vec4: ...
def color_convert_float4_to_u32(value: Vec4) -> int: ...
def color_convert_rgb_to_hsv(r: float, g: float, b: float) -> tuple[float, float, float]: ...
def color_convert_hsv_to_rgb(h: float, s: float, v: float) -> tuple[float, float, float]: ...
def get_color_u32(idx: int, alpha_mul: float = ...) -> int: ...
def get_color_u32_vec4(col: Vec4) -> int: ...
def get_style_color_vec4(idx: int) -> Vec4: ...


# Trees / tabs / tables
def tree_node(label: str) -> bool: ...
def tree_node_ex(label: str, flags: int = ...) -> bool: ...
def tree_push(str_id: str) -> None: ...
def tree_push_ptr(ptr_id: object) -> None: ...
def tree_pop() -> None: ...
def get_tree_node_to_label_spacing() -> float: ...
def set_next_item_open(is_open: bool, cond: int = ...) -> None: ...
def set_next_item_storage_id(storage_id: int) -> None: ...
def tree_node_get_open(storage_id: int) -> bool: ...
def collapsing_header(label: str, flags: int = ...) -> bool: ...
def begin_tab_bar(str_id: str, flags: int = ...) -> bool: ...
def end_tab_bar() -> None: ...
def begin_tab_item(label: str, p_open: object | None = ..., flags: int = ...) -> bool: ...
def begin_tab_item_closable(label: str, p_open: bool = ..., flags: int = ...) -> tuple[bool, bool]: ...
def end_tab_item() -> None: ...
def tab_item_button(label: str, flags: int = ...) -> bool: ...
def set_tab_item_closed(tab_or_docked_window_label: str) -> None: ...
def begin_table(str_id: str, column: int, flags: int = ..., outer_size: Vec2 = ..., inner_width: float = ...) -> bool: ...
def end_table() -> None: ...
def table_next_row(row_flags: int = ..., min_row_height: float = ...) -> None: ...
def table_next_column() -> bool: ...
def table_set_column_index(column_n: int) -> bool: ...
def table_setup_column(label: str, flags: int = ..., init_width_or_weight: float = ..., user_id: int = ...) -> None: ...
def table_setup_scroll_freeze(cols: int, rows: int) -> None: ...
def table_headers_row() -> None: ...
def table_header(label: str) -> None: ...
def table_angled_headers_row() -> None: ...
def table_get_column_count() -> int: ...
def table_get_column_index() -> int: ...
def table_get_row_index() -> int: ...
def table_get_column_name(column_n: int = ...) -> str: ...
def table_get_column_flags(column_n: int = ...) -> int: ...
def table_get_hovered_column() -> int: ...
def table_set_column_enabled(column_n: int, value: bool) -> None: ...
def table_set_bg_color(target: int, color: int, column_n: int = ...) -> None: ...
def get_column_offset(column_index: int = ...) -> float: ...
def table_get_sort_specs() -> TableSortSpecs: ...
def clear_sort_specs_dirty(specs: TableSortSpecs) -> None: ...


# Menus / popups / tooltips
def begin_menu_bar() -> bool: ...
def end_menu_bar() -> None: ...
def begin_main_menu_bar() -> bool: ...
def end_main_menu_bar() -> None: ...
def begin_menu(label: str, enabled: bool = ...) -> bool: ...
def end_menu() -> None: ...
def menu_item(label: str, shortcut: Optional[str] = ..., selected: bool = ..., enabled: bool = ...) -> bool: ...
def open_popup(str_id: str, popup_flags: int = ...) -> None: ...
def open_popup_on_item_click(str_id: Optional[str] = ..., popup_flags: int = ...) -> None: ...
def begin_popup(str_id: str, flags: int = ...) -> bool: ...
def end_popup() -> None: ...
def end_popup_modal() -> None: ...
def begin_popup_modal(name: str, p_open: object | None = ..., flags: int = ...) -> bool: ...
def close_current_popup() -> None: ...
def begin_popup_context_item(str_id: Optional[str] = ..., popup_flags: int = ...) -> bool: ...
def begin_popup_context_window(str_id: Optional[str] = ..., popup_flags: int = ...) -> bool: ...
def begin_popup_context_void(str_id: Optional[str] = ..., popup_flags: int = ...) -> bool: ...
def is_popup_open(str_id: str, flags: int = ...) -> bool: ...
def begin_tooltip() -> bool: ...
def end_tooltip() -> None: ...
def set_tooltip(fmt: str) -> None: ...
def show_tooltip(text: str) -> None: ...
def begin_item_tooltip() -> bool: ...
def set_item_tooltip(fmt: str) -> None: ...


# Cursor / scrolling / IDs / style stack
def get_cursor_pos() -> Vec2: ...
def set_cursor_pos(local_pos: Vec2) -> None: ...
def get_cursor_pos_x() -> float: ...
def set_cursor_pos_x(local_x: float) -> None: ...
def get_cursor_pos_y() -> float: ...
def set_cursor_pos_y(local_y: float) -> None: ...
def get_cursor_screen_pos() -> Vec2: ...
def set_cursor_screen_pos(pos: Vec2) -> None: ...
def get_cursor_start_pos() -> Vec2: ...
def get_scroll_x() -> float: ...
def get_scroll_y() -> float: ...
def set_scroll_x(scroll_x: float) -> None: ...
def set_scroll_y(scroll_y: float) -> None: ...
def set_scroll_here_x(center_x_ratio: float = ...) -> None: ...
def set_scroll_here_y(center_y_ratio: float = ...) -> None: ...
def set_scroll_from_pos_x(local_x: float, center_x_ratio: float = ...) -> None: ...
def set_scroll_from_pos_y(local_y: float, center_y_ratio: float = ...) -> None: ...
def set_next_frame_want_capture_keyboard(want_capture_keyboard: bool) -> None: ...
def set_item_key_owner(key: int) -> bool: ...
def is_mouse_pos_valid(mouse_pos: Vec2 = ...) -> bool: ...
def set_next_frame_want_capture_mouse(want_capture_mouse: bool) -> None: ...
def get_item_id() -> int: ...
def get_item_flags() -> int: ...
def set_item_default_focus() -> None: ...
def set_nav_cursor_visible(visible: bool) -> None: ...
def push_id(str_id: str) -> None: ...
def push_id_int(int_id: int) -> None: ...
def get_id(str_id: str) -> int: ...
def get_id_int(int_id: int) -> int: ...
def pop_id() -> None: ...
def push_style_color(idx: int, color: Vec4) -> None: ...
def pop_style_color(count: int = ...) -> None: ...
def push_style_var(idx: int, val: float) -> None: ...
def push_style_var_vec2(idx: int, val: Vec2) -> None: ...
def push_style_var_x(idx: int, val_x: float) -> None: ...
def push_style_var_y(idx: int, val_y: float) -> None: ...
def pop_style_var(count: int = ...) -> None: ...
def push_item_flag(option: int, enabled: bool) -> None: ...
def pop_item_flag() -> None: ...
def push_item_width(item_width: float) -> None: ...
def pop_item_width() -> None: ...
def set_next_item_width(item_width: float) -> None: ...
def calc_item_width() -> float: ...
def push_text_wrap_pos(wrap_local_pos_x: float = ...) -> None: ...
def pop_text_wrap_pos() -> None: ...
def is_item_hovered(flags: int = ...) -> bool: ...


# Clip rect / clipboard / time / debug
def push_clip_rect(clip_rect_min: Vec2, clip_rect_max: Vec2, intersect_with_current_clip_rect: bool) -> None: ...
def pop_clip_rect() -> None: ...
def get_text_line_height() -> float: ...
def get_text_line_height_with_spacing() -> float: ...
def calc_text_size(text: str, text_end: Optional[str] = ..., hide_text_after_double_hash: bool = ..., wrap_width: float = ...) -> Vec2: ...
def get_font() -> object: ...
def get_font_tex_uv_white_pixel() -> Vec2: ...
def set_window_font_scale(scale: float) -> None: ...
def get_clipboard_text() -> str: ...
def set_clipboard_text(text: str) -> None: ...
def log_to_tty(auto_open_depth: int = ...) -> None: ...
def log_to_file(auto_open_depth: int = ..., filename: Optional[str] = ...) -> None: ...
def log_to_clipboard(auto_open_depth: int = ...) -> None: ...
def log_buttons() -> None: ...
def log_finish() -> None: ...
def get_time() -> float: ...
def get_frame_count() -> int: ...
def load_ini_settings_from_disk(ini_filename: str) -> None: ...
def load_ini_settings_from_memory(ini_data: str, ini_size: int = ...) -> None: ...
def save_ini_settings_to_disk(ini_filename: str) -> None: ...
def save_ini_settings_to_memory() -> str: ...
def show_demo_window() -> None: ...
def show_metrics_window() -> None: ...
def show_debug_log_window() -> None: ...
def show_id_stack_tool_window() -> None: ...
def show_about_window() -> None: ...
def show_style_editor() -> None: ...
def show_user_guide() -> None: ...
def debug_flash_style_color(idx: int) -> None: ...
def debug_start_item_picker() -> None: ...
def debug_text_encoding(text: str) -> None: ...


# Draw-list helpers. These operate on the current window draw list.
def draw_list_add_line(x1: float, y1: float, x2: float, y2: float, col: int, thickness: float = ...) -> None: ...
def draw_list_add_rect(x1: float, y1: float, x2: float, y2: float, col: int, rounding: float = ..., flags: int = ..., thickness: float = ...) -> None: ...
def draw_list_add_rect_filled(x1: float, y1: float, x2: float, y2: float, col: int, rounding: float = ..., flags: int = ...) -> None: ...
def draw_list_add_circle(x: float, y: float, radius: float, col: int, num_segments: int = ..., thickness: float = ...) -> None: ...
def draw_list_add_circle_filled(x: float, y: float, radius: float, col: int, num_segments: int = ...) -> None: ...
def draw_list_add_text(x: float, y: float, col: int, text: str) -> None: ...
def draw_list_add_triangle(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float, col: int, thickness: float = ...) -> None: ...
def draw_list_add_triangle_filled(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float, col: int) -> None: ...
def draw_list_add_quad(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float, x4: float, y4: float, col: int, thickness: float = ...) -> None: ...
def draw_list_add_quad_filled(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float, x4: float, y4: float, col: int) -> None: ...
def draw_list_add_line_h(a: float, b: float, y: float, col: int, thickness: float = ...) -> None: ...
def draw_list_add_line_v(x: float, a: float, b: float, col: int, thickness: float = ...) -> None: ...
def draw_list_add_ellipse(cx: float, cy: float, rx: float, ry: float, col: int, rot: float = ..., num_segments: int = ..., thickness: float = ...) -> None: ...
def draw_list_add_ellipse_filled(cx: float, cy: float, rx: float, ry: float, col: int, rot: float = ..., num_segments: int = ...) -> None: ...
def draw_list_add_bezier_cubic(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float, x4: float, y4: float, col: int, thickness: float = ..., num_segments: int = ...) -> None: ...
def draw_list_add_bezier_quadratic(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float, col: int, thickness: float = ..., num_segments: int = ...) -> None: ...
def path_clear() -> None: ...
def path_line_to(pos: Vec2) -> None: ...
def path_arc_to(center: Vec2, radius: float, a_min: float, a_max: float, num_segments: int = ...) -> None: ...
def path_elliptical_arc_to(center: Vec2, radius: Vec2, rot: float, a_min: float, a_max: float, num_segments: int = ...) -> None: ...
def path_bezier_cubic_curve_to(p2: Vec2, p3: Vec2, p4: Vec2, num_segments: int = ...) -> None: ...
def path_bezier_quadratic_curve_to(p2: Vec2, p3: Vec2, num_segments: int = ...) -> None: ...
def path_fill_convex(col: int) -> None: ...
def path_stroke(col: int, flags: int = ..., thickness: float = ...) -> None: ...


# Dynamic fallback for any binding not yet spelled out in this stub.
def __getattr__(name: str) -> Any: ...
